
debug: true

server:
  error:
    whitelabel:
      enabled: false
    path: "/error"
  port: 8081
  servlet:
    context-path: "/template"

spring:
  mvc:
    pathmatch:
      matching-strategy: "ANT_PATH_MATCHER"

#  http://localhost:8081/template/swagger-ui/